<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 static/models/Horse.glb --root /models/horse/ --output src/lib/assets/models/
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf, useGltfAnimations } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("/models/Horse.glb");
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="AuxScene">
      <T.Mesh
        name="mesh_0"
        geometry={gltf.nodes.mesh_0.geometry}
        material={gltf.nodes.mesh_0.material}
        morphTargetDictionary={gltf.nodes.mesh_0.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.mesh_0.morphTargetInfluences}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
