<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 static/models/projector/scene.gltf --root /models/projector/ --output src/lib/assets/models/
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-beamer-low-poly-c1c504db02e445d3bcd421cdc4d063d2
Title: Old Beamer (Low-Poly)
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("/models/projector/scene.gltf");

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Group scale={0.13}>
        <T.Mesh
          geometry={gltf.nodes.Plane547_0.geometry}
          material={gltf.materials["Material.047"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Plane547_1.geometry}
          material={gltf.materials["Material.054"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Plane547_2.geometry}
          material={gltf.materials["Material.058"]}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
